version: '3.8'
services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tmdb-api
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: redis
    restart: always
    ports:
      - 6380:6379

volumes:
  postgres:
    name: nest-prisma-docker-db
